// Mocks generated by Mockito 5.4.5 from annotations
// in image_convert/test/sprint/mocks/mocked_itens_sprint_controllers.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:firebase_database/firebase_database.dart' as _i4;
import 'package:image_convert/app/modules/authentication/data/firebase_authentication/auth.dart'
    as _i3;
import 'package:image_convert/app/modules/sprint/domain/repositories/interfaces/load_todo_itens_repository_interface.dart'
    as _i2;
import 'package:image_convert/app/modules/sprint/presentation/view/state/controllers/itens_sprint_controller.dart'
    as _i6;
import 'package:mobx/mobx.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIloadTodoItensRepository_0 extends _i1.SmartFake
    implements _i2.IloadTodoItensRepository {
  _FakeIloadTodoItensRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuth_1 extends _i1.SmartFake implements _i3.Auth {
  _FakeAuth_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseReference_2 extends _i1.SmartFake
    implements _i4.DatabaseReference {
  _FakeDatabaseReference_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_3 extends _i1.SmartFake
    implements _i5.ReactiveContext {
  _FakeReactiveContext_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ItensSprintController].
///
/// See the documentation for Mockito's code generation for more information.
class MockItensSprintController extends _i1.Mock
    implements _i6.ItensSprintController {
  @override
  _i2.IloadTodoItensRepository get todoItensRepository => (super.noSuchMethod(
        Invocation.getter(#todoItensRepository),
        returnValue: _FakeIloadTodoItensRepository_0(
          this,
          Invocation.getter(#todoItensRepository),
        ),
        returnValueForMissingStub: _FakeIloadTodoItensRepository_0(
          this,
          Invocation.getter(#todoItensRepository),
        ),
      ) as _i2.IloadTodoItensRepository);

  @override
  set resultInProgress(List<String>? value) => super.noSuchMethod(
        Invocation.setter(
          #resultInProgress,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set resultInitial(List<String>? value) => super.noSuchMethod(
        Invocation.setter(
          #resultInitial,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set conclued(List<String>? value) => super.noSuchMethod(
        Invocation.setter(
          #conclued,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loadTaskFuture(_i5.ObservableFuture<void>? value) => super.noSuchMethod(
        Invocation.setter(
          #loadTaskFuture,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loadprogessFuture(_i5.ObservableFuture<void>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #loadprogessFuture,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loadconcludesFuture(_i5.ObservableFuture<void>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #loadconcludesFuture,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Auth get firebaseAuth => (super.noSuchMethod(
        Invocation.getter(#firebaseAuth),
        returnValue: _FakeAuth_1(
          this,
          Invocation.getter(#firebaseAuth),
        ),
        returnValueForMissingStub: _FakeAuth_1(
          this,
          Invocation.getter(#firebaseAuth),
        ),
      ) as _i3.Auth);

  @override
  set firebaseAuth(_i3.Auth? _firebaseAuth) => super.noSuchMethod(
        Invocation.setter(
          #firebaseAuth,
          _firebaseAuth,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i4.DatabaseReference get refToDo => (super.noSuchMethod(
        Invocation.getter(#refToDo),
        returnValue: _FakeDatabaseReference_2(
          this,
          Invocation.getter(#refToDo),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_2(
          this,
          Invocation.getter(#refToDo),
        ),
      ) as _i4.DatabaseReference);

  @override
  _i4.DatabaseReference get refInProgress => (super.noSuchMethod(
        Invocation.getter(#refInProgress),
        returnValue: _FakeDatabaseReference_2(
          this,
          Invocation.getter(#refInProgress),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_2(
          this,
          Invocation.getter(#refInProgress),
        ),
      ) as _i4.DatabaseReference);

  @override
  _i4.DatabaseReference get refConcludes => (super.noSuchMethod(
        Invocation.getter(#refConcludes),
        returnValue: _FakeDatabaseReference_2(
          this,
          Invocation.getter(#refConcludes),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_2(
          this,
          Invocation.getter(#refConcludes),
        ),
      ) as _i4.DatabaseReference);

  @override
  _i5.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_3(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeReactiveContext_3(
          this,
          Invocation.getter(#context),
        ),
      ) as _i5.ReactiveContext);

  @override
  _i8.Future<void> toDoItem(
    String? item,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDoItem,
          [
            item,
            index,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadInProgress(
    String? itens,
    int? index,
    bool? isRight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadInProgress,
          [
            itens,
            index,
            isRight,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> changeToConclued(
    String? itens,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeToConclued,
          [
            itens,
            index,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteItenToDO(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteItenToDO,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteItenInProgress(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteItenInProgress,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteconcludes(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteconcludes,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadTask() => (super.noSuchMethod(
        Invocation.method(
          #loadTask,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadTaskFromDatabase() => (super.noSuchMethod(
        Invocation.method(
          #loadTaskFromDatabase,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadProgressTaskFromDatabase() => (super.noSuchMethod(
        Invocation.method(
          #loadProgressTaskFromDatabase,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> loadConcludesTaskFromDatabase() => (super.noSuchMethod(
        Invocation.method(
          #loadConcludesTaskFromDatabase,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
