// Mocks generated by Mockito 5.4.5 from annotations
// in image_convert/test/modules/authentication/mocks/controllers/mocked_auth_controller.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:image_convert/app/modules/authentication/domain/repositories/interfaces/auth_repository_interface.dart'
    as _i2;
import 'package:image_convert/app/modules/authentication/presentation/state/auth_controller.dart'
    as _i5;
import 'package:image_convert/app/modules/splash/domain/repository/user_authentication_verification_repository.dart'
    as _i4;
import 'package:image_convert/app/modules/splash/presentation/view/state/controller/register_user_controller.dart'
    as _i7;
import 'package:mobx/mobx.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIauthRepository_0 extends _i1.SmartFake
    implements _i2.IauthRepository {
  _FakeIauthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_1 extends _i1.SmartFake
    implements _i3.ReactiveContext {
  _FakeReactiveContext_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIuserAuthenticationVerificationRepository_2 extends _i1.SmartFake
    implements _i4.IuserAuthenticationVerificationRepository {
  _FakeIuserAuthenticationVerificationRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i5.AuthController {
  @override
  _i2.IauthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeIauthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeIauthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.IauthRepository);

  @override
  set signInSucess(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #signInSucess,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set createAccountSucess(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #createAccountSucess,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loadSignFuture(_i3.ObservableFuture<void>? value) => super.noSuchMethod(
        Invocation.setter(
          #loadSignFuture,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set creatUser(String? _creatUser) => super.noSuchMethod(
        Invocation.setter(
          #creatUser,
          _creatUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set failureCreateUser(String? _failureCreateUser) => super.noSuchMethod(
        Invocation.setter(
          #failureCreateUser,
          _failureCreateUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_1(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeReactiveContext_1(
          this,
          Invocation.getter(#context),
        ),
      ) as _i3.ReactiveContext);

  @override
  _i6.Future<void> signFuture({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signFuture,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> createAccount({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void listenStateSignIn({
    required Function? onSuccess,
    required Function? onFailure,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenStateSignIn,
          [],
          {
            #onSuccess: onSuccess,
            #onFailure: onFailure,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RegisterUserController].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUserController extends _i1.Mock
    implements _i7.RegisterUserController {
  @override
  _i4.IuserAuthenticationVerificationRepository get repository =>
      (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeIuserAuthenticationVerificationRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub:
            _FakeIuserAuthenticationVerificationRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.IuserAuthenticationVerificationRepository);

  @override
  set repository(_i4.IuserAuthenticationVerificationRepository? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #repository,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set registered(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #registered,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set errorOnLoad(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #errorOnLoad,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_1(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeReactiveContext_1(
          this,
          Invocation.getter(#context),
        ),
      ) as _i3.ReactiveContext);

  @override
  _i6.Future<void> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> verifyUser() => (super.noSuchMethod(
        Invocation.method(
          #verifyUser,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
