// Mocks generated by Mockito 5.4.5 from annotations
// in image_convert/test/modules/authentication/mocks/repository/mocked_auth_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:image_convert/app/modules/authentication/data/data_sources/interfaces/auth_data_source_interface.dart'
    as _i2;
import 'package:image_convert/app/modules/authentication/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIauthDataSource_0 extends _i1.SmartFake
    implements _i2.IauthDataSource {
  _FakeIauthDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  @override
  _i2.IauthDataSource get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _FakeIauthDataSource_0(
          this,
          Invocation.getter(#dataSource),
        ),
        returnValueForMissingStub: _FakeIauthDataSource_0(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as _i2.IauthDataSource);

  @override
  _i5.Future<_i3.Either<String, String>> signInWithEmailAndpasswordRepository({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndpasswordRepository,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i3.Either<String, String>>.value(
            _FakeEither_1<String, String>(
          this,
          Invocation.method(
            #signInWithEmailAndpasswordRepository,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Either<String, String>>.value(
            _FakeEither_1<String, String>(
          this,
          Invocation.method(
            #signInWithEmailAndpasswordRepository,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<String, String>>);

  @override
  _i5.Future<_i3.Either<String, String>>
      createUserWithEmailAndPasswordRepository({
    required String? email,
    required String? password,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #createUserWithEmailAndPasswordRepository,
              [],
              {
                #email: email,
                #password: password,
              },
            ),
            returnValue: _i5.Future<_i3.Either<String, String>>.value(
                _FakeEither_1<String, String>(
              this,
              Invocation.method(
                #createUserWithEmailAndPasswordRepository,
                [],
                {
                  #email: email,
                  #password: password,
                },
              ),
            )),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<String, String>>.value(
                    _FakeEither_1<String, String>(
              this,
              Invocation.method(
                #createUserWithEmailAndPasswordRepository,
                [],
                {
                  #email: email,
                  #password: password,
                },
              ),
            )),
          ) as _i5.Future<_i3.Either<String, String>>);
}
